# -*- coding: utf-8 -*-
"""Added_parts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hxU2t0uNiB9B-XLkn81FVlsSlksF2mu-
"""

#from google.colab import files

#files.upload()

#files.upload()

import pandas as pd

excel_file= 'Bangalore section DEc17 2019.xlsx'

file= pd.read_excel(excel_file)

df=pd.DataFrame(file)

f = open('mangalore_div_city_list.txt', 'r')
lines = f.read().split('\n')
f.close()

while("" in lines) : 
    lines.remove("")

exp_list='(.*Udupi.*)'

for str in lines:
  exp_list=exp_list+'|(.*'+str+'.*)'

exp_list

df2=df[df['City'].str.contains(r''+exp_list+'')==True]

df2.to_excel("output.xlsx")

#files.download('output.xlsx')

